"use client";

import React, { useState, useRef } from 'react';
import {
  FileText, User, Phone, Calendar, CheckCircle2,
  Download, Share2, Edit, ArrowRight, ShieldCheck,
  Languages, Zap, Clock, Gavel
} from 'lucide-react';
import { DocFormData } from '@/types';
import { useCase } from '@/context/CaseContext';
import { useLang } from '@/context/LanguageContext';
import jsPDF from 'jspdf';

export default function DocumentsPage() {
  const { addDocument, stateLocation, amount, category } = useCase();
  const { t } = useLang();

  const [formData, setFormData] = useState<DocFormData>({
    yourName: '', yourAddress: stateLocation || '', yourPhone: '', yourEmail: '',
    opponentName: '', opponentAddress: '', opponentPhone: '',
    issueType: category || 'Security Deposit Not Returned', amount: amount || '',
    dateVacated: '', demand: 'Return full deposit', deadline: '15',
    language: 'english', priorComm: false, priorCommDesc: ''
  });

  const [generated, setGenerated] = useState(false);
  const [loading, setLoading]     = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);

  React.useEffect(() => {
    setFormData(prev => ({
      ...prev,
      amount: amount || prev.amount,
      yourAddress: stateLocation || prev.yourAddress,
    }));
  }, [amount, stateLocation]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleGenerate = (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setTimeout(() => {
      setGenerated(true);
      setLoading(false);
      addDocument('Legal Notice');
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }, 1500);
  };

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    const margin = 20;
    const bodyWidth = 170;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(t("documents.legalNotice").toUpperCase(), 105, 30, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    doc.text(t("documents.byRegPost"), 105, 38, { align: 'center' });
    doc.setLineWidth(0.5);
    doc.line(70, 42, 140, 42);
    doc.setFont("helvetica", "bold");
    doc.text(`${t("documents.date")} ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 190, 55, { align: 'right' });
    doc.setFontSize(11);
    doc.text(t("documents.from").toUpperCase(), margin, 65);
    doc.setFont("helvetica", "normal");
    doc.text(`${formData.yourName}\n${formData.yourAddress}\nPhone: ${formData.yourPhone}`, margin, 72);
    doc.setFont("helvetica", "bold");
    doc.text(t("documents.to").toUpperCase(), margin, 100);
    doc.setFont("helvetica", "normal");
    doc.text(`${formData.opponentName}\n${formData.opponentAddress}`, margin, 107);
    doc.setFont("helvetica", "bolditalic");
    const splitSubject = doc.splitTextToSize(`${t("documents.subjectPrefix")} ${formData.issueType} ${t("documents.subjectSuffix")}`, bodyWidth);
    doc.text(splitSubject, margin, 130);
    doc.setFont("helvetica", "normal");
    
    // Process text replacements for template
    const fact2 = t("documents.fact2").replace("{date}", formData.dateVacated ? new Date(formData.dateVacated).toLocaleDateString() : 'N/A').replace("{amount}", amount || formData.amount);
    const fact3 = t("documents.fact3").replace("{demand}", formData.demand.toLowerCase());
    const fact5 = t("documents.fact5").replace("{demand}", formData.demand.toLowerCase()).replace("{deadline}", formData.deadline);
    
    const bodyContent = `${t("documents.sirMadam")}\n\n${t("documents.fact1")}\n\n${fact2}\n\n${fact3}\n\n${t("documents.fact4")}\n\n${fact5}\n\n${t("documents.fact6")}`;
    const splitBody = doc.splitTextToSize(bodyContent.trim(), bodyWidth);
    doc.text(splitBody, margin, 145);
    const footerY = 240;
    doc.setFont("helvetica", "bold");
    doc.text(t("documents.signed"), margin, footerY);
    doc.line(margin, footerY + 15, margin + 50, footerY + 15);
    doc.text(formData.yourName.toUpperCase(), margin, footerY + 22);
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Generated by Chitragupt AI - Legal First-Response System", 105, 285, { align: 'center' });
    doc.save(`Legal_Notice_${formData.yourName || 'User'}.pdf`);
  };

  const handleShareWhatsApp = () => {
    const message = `Hello, I am sharing a Legal Notice regarding my situation: ${formData.issueType}. Powered by Chitragupt AI.`;
    window.open(`https://wa.me/?text=${encodeURIComponent(message)}`, '_blank');
  };

  return (
    <div className="min-h-screen bg-surface py-16 px-6 lg:px-10">
      <div className="max-w-[1280px] mx-auto space-y-10">

        {/* ── Header ── */}
        <div className="text-center space-y-4 animate-fade-up">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#561C24]/5 border border-[#561C24]/10 text-burgundy text-[0.75rem] font-semibold tracking-[0.1em] uppercase">
            <Zap size={13} /><span>{t("documents.aiAssistant")}</span>
          </div>
          <h1 className="text-display text-ink" style={{ fontFamily: 'var(--font-serif)' }}>
            {t("documents.title")}
          </h1>
          <p className="max-w-2xl mx-auto text-[#5C4A42] text-[1.0625rem] leading-[1.7]">
            {t("documents.subtitle")}
          </p>
        </div>

        <div className="w-full h-px bg-[#D4C4B4] opacity-50" />

        <div className="flex flex-col lg:flex-row gap-10 items-start">

          {/* ── LEFT: Form or Preview ── */}
          {!generated ? (
            <main className="w-full lg:w-[60%] animate-fade-up" style={{ animationDelay: "100ms" }}>
              <div className="bg-white rounded-[6px] border border-[#D4C4B4] shadow-[0_4px_16px_rgba(42,26,30,0.04)] p-8 sm:p-10">
                <form onSubmit={handleGenerate} className="space-y-10">

                  <section className="space-y-6">
                    <FormSectionHeader num={1} title={t("documents.form.step1")} sub={t("documents.form.step1Sub")} />
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                      <FormInput label={t("documents.form.fullName")} name="yourName" placeholder={t("documents.form.fullNamePlaceholder")} value={formData.yourName} onChange={handleInputChange} required icon={<User size={15} />} />
                      <FormInput label={t("documents.form.phone")} name="yourPhone" placeholder={t("documents.form.phonePlaceholder")} value={formData.yourPhone} onChange={handleInputChange} required icon={<Phone size={15} />} />
                      <div className="sm:col-span-2">
                        <FormTextArea label={t("documents.form.address")} name="yourAddress" placeholder={t("documents.form.addressPlaceholder")} value={formData.yourAddress} onChange={handleInputChange} required />
                      </div>
                    </div>
                  </section>

                  <div className="w-full h-px bg-[#D4C4B4] opacity-30" />

                  <section className="space-y-6">
                    <FormSectionHeader num={2} title={t("documents.form.step2")} sub={t("documents.form.step2Sub")} />
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                      <FormInput label={t("documents.form.oppName")} name="opponentName" placeholder={t("documents.form.oppNamePlaceholder")} value={formData.opponentName} onChange={handleInputChange} required icon={<User size={15} />} />
                      <div className="sm:col-span-2">
                        <FormTextArea label={t("documents.form.oppAddress")} name="opponentAddress" placeholder={t("documents.form.oppAddressPlaceholder")} value={formData.opponentAddress} onChange={handleInputChange} required />
                      </div>
                    </div>
                  </section>

                  <div className="w-full h-px bg-[#D4C4B4] opacity-30" />

                  <section className="space-y-6">
                    <FormSectionHeader num={3} title={t("documents.form.step3")} sub={t("documents.form.step3Sub")} />
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
                      <div className="sm:col-span-2">
                        <FormSelect label={t("documents.form.mainIssue")} name="issueType" value={formData.issueType} onChange={handleInputChange} options={['Security Deposit Not Returned', 'Illegal Eviction', 'Unpaid Salary', 'Consumer Dispute']} />
                      </div>
                      <FormInput label={t("documents.form.amount")} name="amount" type="number" placeholder="50000" value={formData.amount} onChange={handleInputChange} required icon={<span className="text-sm font-bold opacity-70">₹</span>} />
                      <FormInput label={t("documents.form.dateIncident")} name="dateVacated" type="date" value={formData.dateVacated} onChange={handleInputChange} required icon={<Calendar size={15} />} />
                      <div className="sm:col-span-2">
                        <FormSelect label={t("documents.form.demand")} name="demand" value={formData.demand} onChange={handleInputChange} options={['Return full deposit', 'Issue formal apology', 'Replace defective product', 'Pay unpaid salary with interest']} />
                      </div>
                      <FormInput label={t("documents.form.deadline")} name="deadline" type="number" value={formData.deadline} onChange={handleInputChange} required icon={<Clock size={15} />} />
                    </div>
                  </section>

                  <div className="pt-2">
                    <button type="submit" disabled={loading} className="w-full justify-center bg-burgundy hover:bg-maroon text-ivory font-semibold uppercase tracking-[0.1em] text-[0.875rem] py-4 rounded-sm transition-colors flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed">
                      {loading
                        ? <div className="w-5 h-5 border-2 border-ivory/30 border-t-ivory rounded-full animate-spin" />
                        : <><Zap size={18} /><span>{t("documents.form.generateBtn")}</span></>
                      }
                    </button>
                    <p className="text-center mt-4 text-[0.6875rem] font-semibold text-[#6B5A52] uppercase tracking-[0.08em] leading-[1.6]">
                      {t("documents.form.warning")}
                    </p>
                  </div>
                </form>
              </div>
            </main>
          ) : (
            <main className="w-full lg:w-[65%] space-y-6">
              {/* Success Banner */}
              <div className="p-6 bg-[#3B5441] rounded-[4px] text-white flex flex-col sm:flex-row items-center gap-5 shadow-sm animate-fade-up">
                <div className="w-14 h-14 bg-white/10 rounded-full border border-white/20 flex items-center justify-center flex-shrink-0">
                  <CheckCircle2 size={24} />
                </div>
                <div className="text-center sm:text-left space-y-1 flex-1">
                  <h3 className="text-xl font-medium" style={{ fontFamily: 'var(--font-serif)' }}>{t("documents.successTitle")}</h3>
                  <p className="text-sm opacity-90 leading-[1.6] max-w-sm font-sans">
                    {t("documents.successDesc")}
                  </p>
                </div>
                <button onClick={() => setGenerated(false)} className="px-5 py-2.5 bg-white text-[#3B5441] hover:bg-white/90 rounded-[2px] text-[0.6875rem] font-bold uppercase tracking-[0.1em] transition-colors flex items-center gap-1.5 flex-shrink-0">
                  <Edit size={13} /><span>{t("documents.editForm")}</span>
                </button>
              </div>

              {/* Document Preview */}
              <div ref={previewRef} className="bg-white shadow-[0_2px_12px_rgba(0,0,0,0.06)] rounded-[4px] border border-[#D4C4B4] border-t-4 border-t-burgundy p-10 sm:p-14 font-serif text-ink leading-[1.8] min-h-[800px] select-none text-[1.0625rem]">
                <div className="text-center space-y-1 mb-14">
                  <h2 className="text-xl font-bold uppercase tracking-[0.1em] border-b-2 border-ink pb-2 inline-block font-sans">{t("documents.legalNotice")}</h2>
                  <p className="text-[0.875rem] italic pt-2 font-sans opacity-70 border-b-0">{t("documents.byRegPost")}</p>
                </div>
                <div className="flex justify-between items-start mb-10 text-[0.9375rem] font-sans">
                  <div className="space-y-1">
                    <p className="font-bold opacity-70 uppercase tracking-wide text-xs">{t("documents.from")}</p>
                    <p className="font-bold uppercase tracking-wide">{formData.yourName}</p>
                    <p className="max-w-[200px] leading-relaxed italic">{formData.yourAddress}</p>
                  </div>
                  <div className="text-right">
                    <p className="font-bold uppercase tracking-wide opacity-70 text-xs">{t("documents.date")} <span className="text-ink lowercase font-medium">{new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</span></p>
                  </div>
                </div>
                <div className="space-y-1 mb-10 text-[0.9375rem] font-sans">
                  <p className="font-bold opacity-70 uppercase tracking-wide text-xs">{t("documents.to")}</p>
                  <p className="font-bold uppercase tracking-wide">{formData.opponentName}</p>
                  <p className="max-w-[300px] leading-relaxed italic">{formData.opponentAddress}</p>
                </div>
                <div className="mb-10 p-4 bg-[#F5EDE3] border border-[#D4C4B4] rounded-[2px]">
                  <p className="font-bold italic text-burgundy">{t("documents.subjectPrefix")} {formData.issueType} {t("documents.subjectSuffix")}</p>
                </div>
                <div className="space-y-6 text-[1.0625rem] leading-[1.8] text-justify font-medium">
                  <p>{t("documents.sirMadam")}</p>
                  <p>{t("documents.fact1")}</p>
                  <p>{t("documents.fact2").replace("{date}", formData.dateVacated ? new Date(formData.dateVacated).toLocaleDateString() : 'N/A').replace("{amount}", amount || formData.amount)}</p>
                  <p>{t("documents.fact3").replace("{demand}", formData.demand.toLowerCase())}</p>
                  <p>{t("documents.fact4")}</p>
                  <p>{t("documents.fact5").replace("{demand}", formData.demand.toLowerCase()).replace("{deadline}", formData.deadline)}</p>
                  <p>{t("documents.fact6")}</p>
                </div>
                <div className="mt-16 pt-10 font-sans">
                  <p className="font-bold opacity-70 uppercase tracking-wide text-xs">{t("documents.signed")}</p>
                  <div className="mt-12 border-b border-ink/40 w-48" />
                  <p className="font-bold uppercase pt-3 text-[0.8125rem] tracking-[0.1em]">{formData.yourName}</p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex flex-col sm:flex-row items-center gap-4">
                <button onClick={handleDownloadPDF} className="bg-ink hover:bg-black text-ivory w-full sm:w-auto justify-center py-3.5 px-6 rounded-sm text-[0.8125rem] font-semibold uppercase tracking-[0.1em] transition-colors flex items-center gap-2">
                  <Download size={16} /><span>{t("documents.downloadPdf")}</span>
                </button>
                <button onClick={handleShareWhatsApp} className="bg-transparent border border-ink hover:bg-ink hover:text-ivory text-ink w-full sm:w-auto justify-center py-3.5 px-6 rounded-sm text-[0.8125rem] font-semibold uppercase tracking-[0.1em] transition-colors flex items-center gap-2">
                  <Share2 size={16} /><span>{t("documents.shareWhatsapp")}</span>
                </button>
              </div>
            </main>
          )}

          {/* ── RIGHT: Sidebar ── */}
          <aside className="w-full lg:w-[38%] space-y-6 lg:sticky lg:top-24 animate-fade-up" style={{ animationDelay: "200ms" }}>
            <div className="bg-white rounded-[6px] border border-[#D4C4B4] shadow-[0_2px_8px_rgba(42,26,30,0.03)] p-7 space-y-6">
              <h4 className="text-[1.25rem] text-ink flex items-center gap-2" style={{ fontFamily: 'var(--font-serif)' }}>
                <ShieldCheck size={20} className="text-burgundy" />
                {t("documents.sidebar.whyWorks")}
              </h4>
              <div className="space-y-5">
                <Feature icon={<Clock />} title={t("documents.sidebar.evidenceTitle")} desc={t("documents.sidebar.evidenceDesc")} />
                <Feature icon={<Languages />} title={t("documents.sidebar.bilingualTitle")} desc={t("documents.sidebar.bilingualDesc")} />
                <Feature icon={<CheckCircle2 />} title={t("documents.sidebar.accuracyTitle")} desc={t("documents.sidebar.accuracyDesc")} />
              </div>
              <div className="w-full h-px bg-[#D4C4B4] opacity-40" />
              <div className="space-y-3">
                <p className="text-[0.6875rem] uppercase tracking-[0.1em] font-semibold text-[#6B5A52]">{t("documents.sidebar.nextSteps")}</p>
                <div className="space-y-2.5">
                  <NextStep num="1" text={t("documents.sidebar.step1")} />
                  <NextStep num="2" text={t("documents.sidebar.step2")} />
                  <NextStep num="3" text={t("documents.sidebar.step3")} />
                  <NextStep num="4" text={t("documents.sidebar.step4")} />
                </div>
              </div>
            </div>

            <div className="bg-burgundy text-cream p-8 rounded-[4px] space-y-5 relative overflow-hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-[#F5EDE3]/5 rounded-full blur-2xl" />
              <h4 className="text-2xl text-cream" style={{ fontFamily: 'var(--font-serif)' }}>{t("documents.sidebar.readyToSend")}</h4>
              <p className="text-[0.9375rem] text-cream/70 leading-[1.7] max-w-[90%]">
                {t("documents.sidebar.readyDesc")}
              </p>
              <button className="flex items-center gap-2 text-ivory text-[0.8125rem] font-semibold uppercase tracking-[0.08em] border-b border-ivory/40 pb-0.5 hover:gap-3 transition-all pt-2">
                <span>{t("documents.sidebar.readGuide")}</span>
                <ArrowRight size={14} />
              </button>
            </div>
          </aside>

        </div>
      </div>
    </div>
  );
}

/* ── Helper Components ───────────────────────────────────────── */

function FormSectionHeader({ num, title, sub }: { num: number; title: string; sub: string }) {
  return (
    <div className="flex items-start gap-4">
      <div className="w-8 h-8 rounded-full bg-ivory text-burgundy border border-[#C7B7A3] flex items-center justify-center font-serif flex-shrink-0 text-lg">
        {num}
      </div>
      <div className="space-y-1 mt-0.5">
        <h4 className="text-[1.25rem] text-ink leading-none" style={{ fontFamily: 'var(--font-serif)' }}>{title}</h4>
        <p className="text-[0.875rem] text-[#6B5A52]">{sub}</p>
      </div>
    </div>
  );
}

function FormInput({ label, icon, ...props }: any) {
  return (
    <div className="space-y-2">
      <label className="flex items-center gap-1.5 text-[0.8125rem] font-medium text-ink/70">
        {React.cloneElement(icon, { size: 14, className: "opacity-60" })}
        {label}
      </label>
      <input 
        {...props} 
        className="w-full bg-transparent border-b border-[#D4C4B4] rounded-none px-0 py-2.5 outline-none focus:border-burgundy focus:shadow-[0_1px_0_#561C24] transition-all text-[0.9375rem] text-ink placeholder:text-[#8B7B6B]" 
      />
    </div>
  );
}

function FormTextArea({ label, ...props }: any) {
  return (
    <div className="space-y-2">
      <label className="text-[0.8125rem] font-medium text-ink/70 ml-1 block">
        {label}
      </label>
      <textarea 
        {...props} 
        rows={3} 
        className="w-full bg-ivory border border-[#D4C4B4] rounded-[4px] p-3 outline-none focus:border-burgundy focus:ring-1 focus:ring-burgundy transition-all text-[0.9375rem] text-ink placeholder:text-[#8B7B6B] resize-y" 
      />
    </div>
  );
}

function FormSelect({ label, options, ...props }: any) {
  return (
    <div className="space-y-2">
      <label className="text-[0.8125rem] font-medium text-ink/70 ml-1 block">{label}</label>
      <select 
        {...props} 
        className="w-full bg-ivory border border-[#D4C4B4] rounded-[4px] p-3 outline-none focus:border-burgundy focus:ring-1 focus:ring-burgundy transition-all text-[0.9375rem] text-ink cursor-pointer"
      >
        {options.map((opt: string) => <option key={opt} value={opt}>{opt}</option>)}
      </select>
    </div>
  );
}

function Feature({ icon, title, desc }: any) {
  return (
    <div className="flex gap-4">
      <div className="w-10 h-10 rounded-[4px] bg-ivory border border-[#D4C4B4] text-burgundy flex items-center justify-center flex-shrink-0">
        {React.cloneElement(icon, { size: 18 })}
      </div>
      <div className="space-y-1 pt-0.5">
        <h5 className="text-[0.9375rem] font-bold text-ink">{title}</h5>
        <p className="text-[0.875rem] text-[#5C4A42] leading-[1.6]">{desc}</p>
      </div>
    </div>
  );
}

function NextStep({ num, text }: { num: string; text: string }) {
  return (
    <div className="flex items-center gap-3 group cursor-pointer p-2 -mx-2 hover:bg-ivory rounded-[4px] transition-colors border border-transparent hover:border-[#D4C4B4]">
      <div className="w-5 h-5 rounded-full bg-burgundy/10 border border-burgundy/20 flex items-center justify-center text-[0.6875rem] font-bold text-burgundy group-hover:bg-burgundy group-hover:text-cream transition-colors flex-shrink-0">
        {num}
      </div>
      <p className="text-[0.875rem] font-medium text-[#5C4A42] group-hover:text-ink transition-colors">
        {text}
      </p>
    </div>
  );
}
